name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test the action
    steps:
    - uses: actions/checkout@v2
    - uses: Dovyski/setup-opencv-action@v1
      with:
        opencv-version: '3.4.16'
    - name: Upload Build directory
      uses: actions/upload-artifact@main
      with:
        name: Updat File
        path: /home/runner/work/opcvtest/opcvtest/opencv/build
        
