name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test the action
    steps:
    - uses: actions/checkout@v1
    - uses: Dovyski/setup-opencv-action@v2
    - name: Install OpenCV
      uses: ./ # Uses an action in the root directory
      with:
        opencv-version: '3.4.16'
